source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

platform :ios, '8.0'

target 'XOBaseLib_Example' do
  pod 'XOBaseLib', :path => '../'

  target 'XOBaseLib_Tests' do
    inherit! :search_paths

    
  end
end
